<?php

return [
    'canonical_url' => env('FLOWERFLOW_CANONICAL_URL', 'https://app.flowerflow.com.mx'),
    'timezone' => env('FLOWERFLOW_TIMEZONE', 'America/Hermosillo'),
    'submissions_close_at' => env('FLOWERFLOW_SUBMISSIONS_CLOSE_AT', '2026-08-23 23:59:59'),
    'organization' => [
        'legal_name' => 'FUNXT, A.C.',
        'rfc' => 'FUN110208BT0',
        'commercial_name' => 'FLORECE HERMOSILLO',
        'citizen_movement' => 'FLOWER FLOW',
        'address' => 'ESPOLI 6 TOSCANA, BLVD. MORELOS Y SANTA CECILIA, C.P. 83143, Hermosillo, Sonora, México.',
    ],
    'legal_documents' => [
        'mechanics' => [
            'title' => 'Mecánica y convocatoria',
            'version' => '1.1',
            'path' => 'documentos/2026/01_Mecanica_Convocatoria_Hermosillo_Florece_2026_v1.1.pdf',
            'sha256' => '11c399ca84735d7dbcb17174e192582c93589afa5100c0250753ca15def4db36',
            'effective_at' => '2026-08-14 00:00:00',
        ],
        'terms' => [
            'title' => 'Términos y condiciones',
            'version' => '1.1',
            'path' => 'documentos/2026/02_Terminos_y_Condiciones_Plataforma_Flower_Flow_2026_v1.1.pdf',
            'sha256' => '4e3e6c272f9459b934004168bfccc26d6759a4dbce6c804c03afbb86cda6b144',
            'effective_at' => '2026-08-14 00:00:00',
        ],
        'privacy' => [
            'title' => 'Aviso de privacidad integral',
            'version' => '1.1',
            'path' => 'documentos/2026/03_Aviso_de_Privacidad_Plataforma_Flower_Flow_2026_v1.1.pdf',
            'sha256' => '041ae9704f80a0108ee69bb39b8646ee8098134573a730f801e4057642ae2da1',
            'effective_at' => '2026-08-11 00:00:00',
        ],
    ],
    'flags' => [
        'public' => env('FLOWERFLOW_PUBLIC_ENABLED', true),
        'registration' => env('FLOWERFLOW_REGISTRATION_ENABLED', false),
        'submissions' => env('FLOWERFLOW_SUBMISSIONS_ENABLED', false),
        'results' => env('FLOWERFLOW_RESULTS_ENABLED', false),
        'panel' => env('FLOWERFLOW_PANEL_ENABLED', true),
        'admissibility_review' => env('FLOWERFLOW_ADMISSIBILITY_REVIEW_ENABLED', false),
        'evaluation' => env('FLOWERFLOW_EVALUATION_ENABLED', false),
    ],
    'security' => [
        'enforce_strict_csp' => env('FLOWERFLOW_CSP_ENFORCE_STRICT', false),
        'hsts_max_age' => (int) env('FLOWERFLOW_HSTS_MAX_AGE', 86400),
    ],
    'limits' => [
        'team_members' => (int) env('FLOWERFLOW_MAX_TEAM_MEMBERS', 5),
        'submissions_per_user' => (int) env('FLOWERFLOW_MAX_SUBMISSIONS_PER_USER', 4),
        'upload_kib' => (int) env('FLOWERFLOW_MAX_UPLOAD_KIB', 10240),
        'submission_title_characters' => 180,
        'submission_summary_characters' => 500,
        'submission_description_html_characters' => 20000,
        'submission_description_text_characters' => 12000,
    ],
    'category_icons' => [
        'movilidad-con-flow' => 'ri-bus-line',
        'hermosillo-florece' => 'ri-seedling-line',
        'mi-familia-mi-mascota' => 'ri-bear-smile-line',
        'hermosillo-sin-barreras' => 'ri-accessibility-line',
    ],
    'allowed_document_extensions' => [
        'pdf', 'doc', 'docx', 'odt', 'ppt', 'pptx', 'odp', 'xls', 'xlsx', 'ods',
    ],
    'allowed_editor_image_extensions' => ['jpg', 'jpeg', 'png', 'webp'],
    'admissibility' => [
        'clarification_response_characters' => 2000,
        'files_per_person_request' => 3,
        'files_total_kib_per_person_request' => 10240,
        'file_extensions' => ['pdf', 'jpg', 'jpeg', 'png', 'webp'],
        'residency_disk' => 'residency',
        'clarification_disk' => 'clarifications',
        'retention_days' => 90,
    ],
    'external_links' => [
        'video_hosts' => ['youtube.com', 'www.youtube.com', 'youtu.be'],
        'folder_hosts' => ['drive.google.com', 'www.dropbox.com', 'dropbox.com', 'onedrive.live.com'],
    ],
    'exports' => [
        'disk' => env('FLOWERFLOW_EXPORT_DISK', 'exports'),
        'retention_hours' => (int) env('FLOWERFLOW_EXPORT_RETENTION_HOURS', 24),
        'queue_connection' => env('FLOWERFLOW_EXPORT_QUEUE_CONNECTION', 'database'),
        'queue' => env('FLOWERFLOW_EXPORT_QUEUE', 'exports'),
        'tries' => (int) env('FLOWERFLOW_EXPORT_TRIES', 3),
        'timeout' => (int) env('FLOWERFLOW_EXPORT_JOB_TIMEOUT', 120),
        'backoff' => [60, 300],
    ],
    'mail' => [
        'from' => env('MAIL_FROM_ADDRESS', 'notificaciones@flowerflow.com.mx'),
        'reply_to' => env('MAIL_REPLY_TO_ADDRESS', 'convocatoria@flowerflow.com.mx'),
        'reply_to_name' => env('MAIL_REPLY_TO_NAME', 'FLOWER FLOW'),
        'privacy_reply_to' => env('PRIVACY_REPLY_TO_ADDRESS', 'privacidad@flowerflow.com.mx'),
        'queue_connection' => env('FLOWERFLOW_MAIL_QUEUE_CONNECTION', 'database'),
        'queue' => env('FLOWERFLOW_MAIL_QUEUE', 'default'),
        'tries' => (int) env('FLOWERFLOW_MAIL_TRIES', 4),
        'timeout' => (int) env('FLOWERFLOW_MAIL_JOB_TIMEOUT', 30),
        'backoff' => [60, 300, 900],
    ],
];
