@extends('layouts.flowerflow')
@section('title', $submission->exists ? 'Editar propuesta' : 'Nueva propuesta')
@section('content')
@php
  $isEdit = $submission->exists;
  $links = $isEdit ? $submission->externalLinks->keyBy('kind') : collect();
  $members = $isEdit && $submission->team ? $submission->team->members->where('is_representative', false)->values() : collect();
  $oldMembers = old('team_members', $members->map(fn($m) => ['full_name' => $m->full_name, 'email' => $m->email])->all());
@endphp
<div class="mb-4"><p class="ff-kicker mb-1">Borrador editable</p><h1>{{ $isEdit ? 'Editar propuesta' : 'Nueva propuesta' }}</h1><p>Los borradores no cuentan como envío. Revisa todo y finaliza para obtener un folio.</p></div>
<form method="POST" action="{{ $isEdit ? route('submissions.update', $submission) : route('submissions.store') }}" enctype="multipart/form-data" class="card ff-card p-4">
  @csrf
  @if($isEdit)
    @method('PUT')
  @endif
  <fieldset><legend class="h3">1. Modalidad y categoría</legend><div class="row g-3"><div class="col-md-6"><label class="form-label" for="participation_type">Participación</label><select class="form-select" id="participation_type" name="participation_type" data-team-toggle="#team-fields" required><option value="individual" @selected(old('participation_type', $submission->participation_type ?: 'individual') === 'individual')>Individual</option><option value="team" @selected(old('participation_type', $submission->participation_type) === 'team')>Equipo</option></select></div><div class="col-md-6"><label class="form-label" for="category_public_id">Categoría</label><select class="form-select" id="category_public_id" name="category_public_id" required><option value="">Selecciona</option>@foreach($competition->categories as $category)<option value="{{ $category->public_id }}" @selected(old('category_public_id', $submission->category?->public_id) === $category->public_id)>{{ $category->name }}</option>@endforeach</select></div></div>
  <div id="team-fields" class="mt-4"><div class="row g-3"><div class="col-12"><label class="form-label" for="team_name">Nombre del equipo</label><input class="form-control" id="team_name" name="team_name" value="{{ old('team_name', $submission->team?->name) }}"></div><div class="col-12"><p class="mb-1"><strong>Integrantes adicionales</strong></p><small>Tu cuenta es la representante y ya cuenta dentro del máximo de cinco.</small></div>@for($i = 0; $i < 4; $i++)<div class="col-md-7"><label class="form-label" for="member_name_{{ $i }}">Integrante {{ $i + 2 }} · nombre</label><input class="form-control" id="member_name_{{ $i }}" name="team_members[{{ $i }}][full_name]" value="{{ $oldMembers[$i]['full_name'] ?? '' }}"></div><div class="col-md-5"><label class="form-label" for="member_email_{{ $i }}">Correo opcional</label><input class="form-control" id="member_email_{{ $i }}" name="team_members[{{ $i }}][email]" type="email" value="{{ $oldMembers[$i]['email'] ?? '' }}"></div>@endfor<div class="col-12"><div class="form-check"><input class="form-check-input" id="team_eligibility" name="team_eligibility" type="checkbox" value="1" @checked(old('team_eligibility'))><label class="form-check-label" for="team_eligibility">Declaro que todas las personas del equipo tienen 18 años o más y residencia comprobable en Hermosillo.</label></div></div></div></div></fieldset>
  <hr class="my-4">
  <fieldset><legend class="h3">2. Proyecto</legend><div class="mb-3"><label class="form-label" for="title">Título del proyecto</label><input class="form-control" id="title" name="title" maxlength="180" value="{{ old('title', $submission->title) }}" required></div><div class="mb-3"><label class="form-label" for="summary">Resumen breve</label><textarea class="form-control" id="summary" name="summary" maxlength="500" rows="3" required>{{ old('summary', $submission->summary) }}</textarea><small>Máximo 500 caracteres; se usa en listados.</small></div><label class="form-label" for="description-editor">Descripción detallada</label><div id="description-editor" data-flowerflow-editor aria-label="Editor de descripción detallada"></div><input type="hidden" name="description_delta" value="{{ old('description_delta', $submission->description_delta ? json_encode($submission->description_delta) : '') }}"><input type="hidden" name="description_html" value="{{ old('description_html', $submission->description_html) }}"><input type="hidden" name="description_text" value="{{ old('description_text', $submission->description_text) }}"></fieldset>
  <hr class="my-4">
  <fieldset><legend class="h3">3. Archivos y enlaces</legend><div class="row g-3"><div class="col-md-6"><label class="form-label" for="documents">Archivos de propuesta</label><input class="form-control" id="documents" name="documents[]" type="file" multiple accept=".pdf,.doc,.docx,.odt,.ppt,.pptx,.odp,.xls,.xlsx,.ods"><small>Al menos uno antes de enviar. Total acumulado: 10 MiB.</small></div><div class="col-md-6"><label class="form-label" for="editor_images">Imágenes para apoyar la descripción</label><input class="form-control" id="editor_images" name="editor_images[]" type="file" multiple accept=".jpg,.jpeg,.png,.webp"><small>JPEG, PNG o WebP; también cuentan en los 10 MiB.</small></div><div class="col-md-6"><label class="form-label" for="youtube_url">Video de YouTube opcional</label><input class="form-control" id="youtube_url" name="youtube_url" type="url" value="{{ old('youtube_url', $links->get('youtube')?->url) }}" placeholder="https://youtu.be/..."></div><div class="col-md-6"><label class="form-label" for="public_folder_url">Carpeta pública opcional</label><input class="form-control" id="public_folder_url" name="public_folder_url" type="url" value="{{ old('public_folder_url', $links->get('public_folder')?->url) }}" placeholder="https://drive.google.com/..."></div></div>@if($isEdit && $submission->files->isNotEmpty())<h3 class="h5 mt-4">Archivos guardados</h3><ul class="list-group">@foreach($submission->files as $file)<li class="list-group-item d-flex justify-content-between align-items-center"><span>{{ $file->original_name }} <small>({{ number_format($file->size_bytes / 1024, 1) }} KiB · {{ $file->kind === 'editor_image' ? 'imagen' : 'documento' }})</small></span><button class="btn btn-sm btn-outline-danger" type="submit" form="delete-file-{{ $file->public_id }}">Eliminar</button></li>@endforeach</ul>@endif<p class="small mt-3 mb-0">La persona participante controla los permisos de enlaces externos. FlowerFlow valida el dominio, pero no descarga ni indexa su contenido.</p></fieldset>
  <div class="mt-4"><button class="btn btn-flower btn-lg">Guardar borrador</button></div>
</form>
@if($isEdit)
  @foreach($submission->files as $file)
    <form id="delete-file-{{ $file->public_id }}" method="POST" action="{{ route('submissions.files.destroy', [$submission, $file]) }}">
      @csrf
      @method('DELETE')
    </form>
  @endforeach
@endif
@endsection
